DROP TABLE IF EXISTS analyzes;
DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS results;
DROP TABLE IF EXISTS vulns;

create table analyzes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status text NOT NULL DEFAULT 'pending',
    message text DEFAULT NULL
);

CREATE TABLE files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    analyze_id INTEGER NOT NULL,
    file_name TEXT NOT NULL,
    hash_name TEXT NOT NULL,
    results_id INTEGER NOT NULL DEFAULT 0
);


create table results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    analyze_id INTEGER NOT NULL,
    module TEXT NOT NULL,
    run_time TEXT DEFAULT NULL,
    progress text DEFAULT NULL
);

create table vulns (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    results_id INTEGER NOT NULL,
    vuln_name TEXT NOT NULL,
    vuln_num TEXT NOT NULL
)